/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Sun Oct 13 19:44:37 2019. */

#include "sensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SensorDataArray_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, SensorDataArray, array, array, &SensorDataArray_SensorData_fields),
    PB_LAST_FIELD
};

const pb_field_t SensorDataArray_SensorData_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, SensorDataArray_SensorData, sensorType, sensorType, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, SensorDataArray_SensorData, value, sensorType, 0),
    PB_FIELD(  3, INT64   , REQUIRED, STATIC  , OTHER, SensorDataArray_SensorData, timeStamp, value, 0),
    PB_LAST_FIELD
};

const pb_field_t Command_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, Command, commandType, commandType, 0),
    PB_FIELD(  2, INT64   , OPTIONAL, STATIC  , OTHER, Command, commandValue, commandType, 0),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SensorDataArray, array[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_SensorDataArray_SensorDataArray_SensorData_Command)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SensorDataArray, array[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_SensorDataArray_SensorDataArray_SensorData_Command)
#endif


/* @@protoc_insertion_point(eof) */
