/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Mon Oct 21 22:20:58 2019. */

#include "simple.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SimpleMessage_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, SimpleMessage, startChar, startChar, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, SimpleMessage, data, startChar, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, SimpleMessage, endChar, data, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
