/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Thu Feb 27 14:40:20 2020. */

#include "simple_message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SimpleMessage_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SimpleMessage, msg, msg, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
